entity: ???
project: ???

program: train.py
method: random
metric:
  name: final_distance  # more dense information compared to success_rate
  goal: minimize

parameters:
  # MLP Model
  agent_config.model_config.inner_model_config.num_layers:
    distribution: int_uniform
    min: 1
    max: 5

  agent_config.model_config.inner_model_config.num_neurons:
    distribution: categorical
    values: [32, 64, 128, 256, 512, 1024]

  # ProDMP
  agent_config.model_config.inner_model_config.prodmp_handler_config.weights_scale:
    distribution: q_uniform
    min: 0.1
    max: 1.0
    q: 0.1
  agent_config.model_config.inner_model_config.prodmp_handler_config.goal_scale:
    distribution: q_uniform
    min: 0.1
    max: 1.0
    q: 0.1
  agent_config.model_config.inner_model_config.prodmp_handler_config.num_basis:
    distribution: int_uniform
    min: 1
    max: 21
  agent_config.model_config.inner_model_config.prodmp_handler_config.tau_factor:
    distribution: q_uniform
    min: 1.0
    max: 5.0
    q: 0.5

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
