_target_: movement_primitive_diffusion.models.prodmp_residual_mlp_inner_model.ProDMPResidualMLPInnerModel
_recursive_: False

defaults:
  - prodmp_handler_config: default_config

state_size: null # set in python based on encoder
action_size: null # set in python based on process_batch

hidden_sizes: [512, 256, 128]
blocks_per_layer: 1
t_pred: ${t_pred}

dropout_rate: 0.0
spectral_norm: False
norm: null
hidden_nonlinearity: LeakyReLU

sigma_embedding_config:
  _target_: movement_primitive_diffusion.networks.sigma_embeddings.SinusoidalEmbedding
  _recursive_: False
  embedding_size: 64
