_target_: movement_primitive_diffusion.models.prodmp_resnet1d_inner_model.ProDMPResNet1DInnerModel
_recursive_: False

defaults:
  - prodmp_handler_config: default_config

state_size: null # set in python based on encoder
action_size: null # set in python based on process_batch

down_sizes: [256, 512, 1024] # for lowdim: [256, 512, 1024], for hybrid *2
kernel_size: 5
n_groups: 8
predict_scale_of_condition: True

# sigma_embedding_config:
#   _target_: movement_primitive_diffusion.networks.sigma_embeddings.FourierFeaturesEmbedding
#   _recursive_: False
#   embedding_size: 128

sigma_embedding_config:
  _target_: movement_primitive_diffusion.networks.sigma_embeddings.SinusoidalEmbedding
  _recursive_: False
  embedding_size: 128
  hidden_size_factor: 4
