_target_: movement_primitive_diffusion.models.causal_transformer_inner_model.CausalTransformer
_recursive_: False

state_size: null # set in python based on encoder
action_size: null # set in python based on process_batch

t_pred: ${t_pred}
t_obs: ${t_obs}
predict_past: ${predict_past}

embedding_size: 256

n_layers: 6
n_heads: 4
n_cond_layers: 0  # -> use an MLP instead of a transformer encoder
dropout_probability_embedding: 0.0
dropout_probability_attention: 0.3

sigma_embedding_config:
  _target_: movement_primitive_diffusion.networks.sigma_embeddings.SinusoidalEmbedding
  _recursive_: False
  embedding_size: ${..embedding_size}
  hidden_size_factor: 4
